[
target.aarch64-unknown-linux-gnu
]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
xargo = false
build = false

[
build.env
]
passthrough = [
    "RUST_LOG",
    "RUST_BACKTRACE",
]