name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          # Existing Linux x86_64 (gnu) build
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rnvm
            asset_name: rnvm-linux-amd64
            use_container: false

          # NEW Linux x86_64 MUSL build
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: rnvm
            asset_name: rnvm-linux-amd64-musl
            use_container: true

          # Windows build
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rnvm.exe
            asset_name: rnvm-windows-amd64.exe
            use_container: false

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rnvm
            asset_name: rnvm-macos-amd64
            use_container: false

          # macOS ARM64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rnvm
            asset_name: rnvm-macos-arm64
            use_container: false

    steps:
      # 1. Check out code
      - uses: actions/checkout@v3

      # 2. Install Rust only if NOT using container
      - name: Install Rust
        if: "!matrix.use_container"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      # 3. Docker-based build (MUSL) – only on Linux
      - name: Build MUSL Binary
        if: matrix.use_container
        uses: addnab/docker-run-action@v3
        with:
          image: messense/rust-musl-cross:x86_64-musl
          options: -v ${{ github.workspace }}:/home/rust/src
          run: |
            cd /home/rust/src
            # If you want vendored OpenSSL or need other system libs, do:
            # apk update && apk add build-base
            cargo build --release --target x86_64-unknown-linux-musl

      # 4. Regular (native) build for other platforms
      - name: Regular Build
        if: "!matrix.use_container"
        run: cargo build --release --target ${{ matrix.target }}

      # 5. Prepare the artifact
      - name: Prepare asset
        run: |
          mkdir -p release
          if [ "${{ matrix.use_container }}" = "true" ]; then
            cp target/x86_64-unknown-linux-musl/release/${{ matrix.artifact_name }} release/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release/${{ matrix.asset_name }}
          fi
        shell: bash

      # 6. Generate a SHA-256 checksum (optional)
      - name: Generate SHA-256
        run: |
          cd release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            certutil -hashfile ${{ matrix.asset_name }} SHA256 > ${{ matrix.asset_name }}.sha256
          else
            shasum -a 256 ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256
          fi
        shell: bash

      # 7. Upload to GitHub Releases
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/${{ matrix.asset_name }}
            release/${{ matrix.asset_name }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
